### ISSUE TITLE
这个App支持扫描本地SD卡或是U盘的歌曲吗？

### ISSUE THREAD

**Issue by Avail0723** [StealFeam/LocalMusic#2]
请问作者，你这个App在Android 8.1上，可以手动扫描SD卡歌曲和U盘的歌曲到媒体库吗？
也就是接口MediaScannerConnection.scanFile的使用

**Comment by Sole2016** [comment]
我没有使用这个api进行扫描，SD卡中的歌曲是可以的，U盘没有试过，有空我会尝试一下。

**Comment by Avail0723** [comment]
项目少上传了一个versions.build文件哦？

**Comment by Sole2016** [comment]
谢谢提醒，稍后文件会补上。删除SD卡文件需要先允许目录权限才行的

**Comment by Avail0723** [comment]
好的，其实，我更想专注你这个项目的扫描歌曲功能，因为我发现Android8.1，在SD卡尚未移除，歌曲内容还存在的情况下，重新扫描歌曲，是没法更新到媒体库的，不知道你有没有研究过这块

**Comment by Sole2016** [comment]
在DataTransform类中的reQueryList方法就是针对媒体库中不存在媒体的识别，我还没有研究如何将这些媒体添加到媒体库中。
